language: rust
rust:
    - stable
    - beta
matrix:
  allow_failures:
    - rust: beta
before_install:
  # This ppa provides cmake 2.8.12, which travis doesn't have yet
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
addons:
  apt:
    packages:
    - libXxf86vm-dev
    - libsdl2-dev
install:
  - sudo apt-get install cmake
script:
  - cargo build
  - cargo test
