language: rust
rust:
    - stable
    - beta
matrix:
  allow_failures:
    - rust: beta
before_install:
  # This ppa provides cmake 2.8.12, which travis doesn't have yet
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake
  - sudo apt-get install libXxf86vm-dev
script:
  - cargo build
  - cargo test
