[package]
name = "pewpew"
version = "0.1.0"
authors = ["Nathan Merritt <gnm@the-merritts.net>"]

repository = "https://github.com/gnmerritt/pewpew"
readme = "README.md"
license = "MIT"

[dependencies]
kiss3d = "0.8.0"
nalgebra = "0.11.0"
nphysics3d = "0.6.0"
